### ISSUE TITLE
Checklist for working proper simulation

### ISSUE THREAD

**Issue by GenrikhEkkerman117** [hamk-uas/logistics_sim#8]
**Containers**
- [ ] Containers grow independently
- [ ] Containers are selected independently 
- [ ] Containers age is increased independently 
**Vehicles**
- [ ] Works no longer than shift max time
- [ ] Stops for a lunch break 
- [ ] "Sleeps" till next shift, starts again after
- [ ] Containers are assigned each morning 
**City**

**Comment by GenrikhEkkerman117** [comment]
Go through that on a meeting together
